### ISSUE TITLE
Migrer bases QDrant Albert API West2 (pas SecNumCloud) vers West2 (SNC)

### ISSUE THREAD

**Issue by ArtixJP** [etalab-ia/OpenGateLLM#100]
Il faut migrer QDrant sans perdre les données de prod (ex : collections publiques, ex : collections privées).

Points d'attention : 
- [ ]
- [ ]

Solution : 
- Dump la base QDrant
- Charger le dump en SecNumCloud
- A compléter...

**Comment by cyrillay** [comment]
Done by @leoguillaume
