### ISSUE TITLE
Avoir un grist au clair sur l'infra

### ISSUE THREAD

**Issue by ArtixJP** [etalab-ia/OpenGateLLM#101]
Mettre à jour le tableau : https://grist.numerique.gouv.fr/o/albert/25SBdE5Sqqhg/Infrastructure/p/2 
notamment en précisant la région (WEST1 ou WEST2) des GPU.

Note : cette mise à jour peut être faite après les migrations.

**Comment by leoguillaume** [comment]
@ArtixJP Est-ce que tu veux une vue aussi par modèle ou la vue des ressources suffies ? 
https://grist.numerique.gouv.fr/o/albert/25SBdE5Sqqhg/Infrastructure/p/16

**Comment by leoguillaume** [comment]
Done: https://grist.numerique.gouv.fr/o/albert/25SBdE5Sqqhg/Infrastructure/p/2
