### ISSUE TITLE
/redoc api documentation is not available

### ISSUE THREAD

**Issue by dtrckd** [etalab-ia/OpenGateLLM#25]
fastapi generate a /docs endpoint as well as a /redoc one, that is often more readable.
Here is an exemple : https://franceservices.dev.etalab.gouv.fr/api/redoc

A reverse proxy is probably hiding it as we got redirected to a streamlit playground.

**Comment by leoguillaume** [comment]
Disponible sur https://albert.api.etalab.gouv.fr/documentation
