### ISSUE TITLE
Mise en place d'un calendrier de déploiements pour Albert API

### ISSUE THREAD

**Issue by leoguillaume** [etalab-ia/OpenGateLLM#60]
# Solution

- Mise en production tous les mardi matin à 10h30 tous les 2 semaines (création d'un event calendar
- Création d'un tag et une release note
- Ajout de ce tag dans github action (tag de l'image)

Prochain tag actuellement : v0.0.1-alpha

**Comment by leoguillaume** [comment]
@Ledoux tu valides ce process ? Tu ajouterais quelque chose ?

**Comment by Ledoux** [comment]
Super,

on peut y aller comme ça.

Je crois qu'avec l'usage, on y ajouterait deux autres dates :
- mise en staging par les DEV
- jour de recette sur staging et validation PO

Et on devrait surement alterner, dans les sprints
- 1ere semaine de sprint le mardi : mise en prod
- 2eme semaine de sprint le mardi : mise en staging

Et pendant la semaine de sprint off, on deploierait rien...Pour avoir la tête libre des possibles hotfixs.
Ca fait une CD à release toutes les 3 semaines.

**Comment by leoguillaume** [comment]
@Ledoux je t'ai envoyé un évenement récurent, je vais me renseigner sur la création de tag pour mardi prochain. Je clos cette US.
